2024-12-09 15:17:35,903 | INFO | "test_challenge" выполнен успешно
2024-12-09 15:17:35,904 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-12-09 15:17:35,905 | WARNING | Traceback (most recent call last):
  File "C:\Users\InterMundos\Documents\GitHub\UrbanUniversity\tests_12_4.py", line 74, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\InterMundos\Documents\GitHub\UrbanUniversity\tests_12_4.py", line 15, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-12-09 15:17:35,907 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-12-09 15:17:35,910 | WARNING | Traceback (most recent call last):
  File "C:\Users\InterMundos\Documents\GitHub\UrbanUniversity\tests_12_4.py", line 63, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\InterMundos\Documents\GitHub\UrbanUniversity\tests_12_4.py", line 20, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

